server:
  servlet:
    context-path: /dev-api
  port: 8080


# DataSource Config
spring:
  datasource:
    # 数据库连接信息
    url: jdbc:mysql://localhost:3306/20260803-demo?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 144312
    driver-class-name: com.mysql.cj.jdbc.Driver
    data:
      redis:
        # ===== 基础配置 =====
        host: 127.0.0.1           # Redis 服务器地址
        port: 6379                # Redis 服务器端口
        password:                 # 密码（无密码留空）
        database: 1               # 数据库索引（0-15）
        timeout: 10s              # 连接超时时间